### ISSUE TITLE
Possible Error in Population script 6.7

### ISSUE THREAD

**Issue by guptamo** [leifos/tango_with_django_book#126]
"To create a population script for Rango’s database, we start by creating a new Python module within our Django project’s root directory (e.g. <workspace>/tango_with_django_project/)."

I'm not sure if I've made a mistake in how I've setup my project however if I create the population script directly in the <workspace> directory everything seems to work fine. I get the following traceback when the population script is placed in the <workspace>/tango_with_django_project/ folder.

(rango)~/Desktop/code/test-project/workspace/tango_with_django_project $python populate_rango.py 
Traceback (most recent call last):
  File "populate_rango.py", line 5, in <module>
    django.setup()
  File "/Users/mohitgupta/.virtualenvs/rango/lib/python2.7/site-packages/django/__init__.py", line 20, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/Users/mohitgupta/.virtualenvs/rango/lib/python2.7/site-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "/Users/mohitgupta/.virtualenvs/rango/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/mohitgupta/.virtualenvs/rango/lib/python2.7/site-packages/django/conf/__init__.py", line 98, in __init__
    % (self.SETTINGS_MODULE, e)
ImportError: Could not import settings 'tango_with_django_project.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named tango_with_django_project.settings

**Comment by leifos** [comment]
My directory structure is:

|- tango_with_django
    |
    |-rango
    |-tango_with_django_project
    |- populate.py


So in populate.py when it calls:

os.environ.setdefault('DJANGO_SETTINGS_MODULE',
'tango_with_django_project.settings')

it looks inside tango_with_django_project and is able to find settings.py

I hope that helps
L

**Comment by guptamo** [comment]
Ahhhh ok that makes sense…it’s basically as I had implemented it. It works!

Maybe it’s just me but the directory structure that you refer to in the book is slightly confusing since when you refer to the root directory you mention   <workspace>/tango_with_django_project/ instead of simply <workspace>. 

I can’t thank you enough for your book. Along with the Django tutorial there are no other sources which are as clear, concise, and informative! Hopefully my feedback finds you well :)
 
Cheers,

Mohit Gupta


On February 21, 2015 at 7:05:11 AM, Leif Azzopardi (notifications@github.com ) wrote:

My directory structure is:

|- tango_with_django
|
|-rango
|-tango_with_django_project
|- populate.py


So in populate.py when it calls:

os.environ.setdefault('DJANGO_SETTINGS_MODULE',
'tango_with_django_project.settings')

it looks inside tango_with_django_project and is able to find settings.py

I hope that helps
L

**Comment by Brunaldo** [comment]
I made the same error as well! Thank you for your help :)

**Comment by maxwelld90** [comment]
Hi Mohit,

Thanks for your feedback! Yeah, I’ve noticed that there may be a few inconsistencies when we reference <workspace> and <workspace>/tango_with_django_project/. This is on my todo, something I’d like to fix ASAP!

Glad you’re enjoying the tutorial.

Cheers,
David
