### ISSUE TITLE
7.3.2.: Update Category Table with Slug Field: A default of '' is not acceptable.

### ISSUE THREAD

**Issue by RevRagnarok** [leifos/tango_with_django_book#137]
I could not just leave the field as just ''. When I did:

```
Running migrations:
  Applying rango.0003_category_slug...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
  File "/home/rr/.virtualenvs/rango/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 485, in execute
...
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: rango_category__new.slug
```

Maybe a newer version of Django is enforcing unique on the slug type?

A quick search resulted in me doing this before the population script:
```
./manage.py flush
./manage.py syncdb
```

**Comment by HassenPy** [comment]
In the [Django 1.7 release notes](https://docs.djangoproject.com/en/dev/releases/1.7/#what-s-new-in-django-1-7), ``syncdb`` is listed as deprecated and replaced with ``migrate``.

**Comment by TekThis** [comment]
I ran into this same issue.  To work around it I turned off the unique requirement for the column, reran the database population script (where the save method added the slug values) and then changed the models file to make the column unique again.

**Comment by ser1us** [comment]
I used a slightly different approach to get rid of this problem. I just allow null values which makes it possible to run the migration without any issues and it's still not possible to enter the same value twice.

Here's my model definition:

    class Category(models.Model):
        name = models.CharField(max_length=128, unique=True)
        views = models.IntegerField(default=0)
        likes = models.IntegerField(default=0)
        slug = models.SlugField(unique=True, blank=True, null=True)

        def save(self, *args, **kwargs):
            self.slug = slugify(self.name)
            super(Category, self).save(*args, **kwargs)

        def __str__(self):
            return self.name

**Comment by dragan011** [comment]
Another approach is to create 3 migrations. 
First update the Category model where new slug field does not have unique constraint. Create schema migration for it using makemigrations.
Second,  create data migration that will populate slug filed according to its definition. To create data migration first create an empty migration using command 'python manage.py makemigrations --empty rango'. Then add following code to it:

# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.template.defaultfilters import slugify

def create_category_slug(apps, schema_editor):
    # We can't import the Category model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Category = apps.get_model("rango", "Category")
    for category in Category.objects.all():
        category.slug = slugify(category.name)
        category.save()

class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_category_slug'),
    ]

    operations = [
        migrations.RunPython(create_category_slug),
    ]

Finally, create third migration after adding unique=True to the slug field.

Now you can run all 3 migrations at once successfully.

This approach is more generic and will work even if you manually added some new Categories that are not part of the populate_categores.py script.

**Comment by hyperknot** [comment]
I was stuck in this issue as well. I got help on #django IRC channel. My solution was to:
1. unique=False, run migrations
2. open shell and run `[cat.save() for cat in Category.objects.all()]`
3. unique=True, run migrations

**Comment by hyperknot** [comment]
`flush` is very strong. it removes all users, etc, which needs to be recreated.

**Comment by Copser** [comment]
Having the same problem, but I have used @ser1us example of model and everything worked like it should.
